### ISSUE TITLE
Default jobset success policy doesn't apply to replicatedJobs with more than 1 replica

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#117]
Currently the success policy is configured to mark a jobset as succeeded if the number of completed jobs == number of replicatedJobs (see [here](https://github.com/kubernetes-sigs/jobset/blob/main/pkg/controllers/jobset_controller.go#L114)). This only works if the replicatedJobs only have 1 replica each. We need to update this to handle the case where each replicatedJob has an arbitrary number of replicas and we want all jobs to complete before marking the jobset as succeeded.

/king bug

**Comment by ahg-g** [comment]
we need to backport the fix
