### ISSUE TITLE
Setting NodeAffinity foreach Job during unsuspend

### ISSUE THREAD

**Issue by mcariatm** [kubernetes-sigs/jobset#134]
**What would you like to be added**:
 Node selectors should be updated on each of jobs based on ReplicatedJob template during unsuspend.
**Why is this needed**:
On suspend and unsuspend process the Node Selectors can be replaced by Kueue Operator.
The JobSet Operator should knows and updates each job before starting them.

**Comment by alculquicondor** [comment]
wdyt @ahg-g @danielvegamyhre?

**Comment by alculquicondor** [comment]
ref https://github.com/kubernetes-sigs/kueue/issues/738

**Comment by ahg-g** [comment]
I think it makes sense, note that currently the template is immutable, so we need to relax that.

**Comment by danielvegamyhre** [comment]
Sounds good to me. On the JobSet side, I think the work can be divided into two tasks:

1. Relax immutability validation for `.spec.replicatedJobs[*].template`
2. Add logic to jobset operator to reconcile the nodeSelectors on the replicatedJob template and the jobs created from that template.

**Comment by mcariatm** [comment]
BTW I propose to add StartTime and PodsReady fields in status.  Any concerns?

**Comment by alculquicondor** [comment]
Can you use conditions and their timestamps?

**Comment by mcariatm** [comment]
Ok, but in on  ResetStatus() should I reset timestamp from condition? how about PodsReady?

**Comment by alculquicondor** [comment]
The API practice is that the timestamp should be reset when there is a transition from true to false or false to true. Is this possible?

**Comment by alculquicondor** [comment]
@kannon92 can you provide some guidance?

**Comment by kannon92** [comment]
> @kannon92 can you provide some guidance?

So my concern is that JobSets control ReplicatedJobs so I don't really understand the `PodsReady`.  We have an issue in k/k to discuss adding a condition when Jobs are Ready (https://github.com/kubernetes/kubernetes/issues/117758).  I think it isn't clear me what this means with replicatedjobs.  For example, you could have 1 replicatedjob fully ready while another one is still starting? 

I would defer to @ahg-g or @danielvegamyhre though.  

> The API practice is that the timestamp should be reset when there is a transition from true to false or false to true. Is this possible?

For Suspend condition for Jobset we do this:

```
func (r *JobSetReconciler) suspendJobSet(ctx context.Context, js *jobset.JobSet, ownedJobs *childJobs) error {
	for _, job := range ownedJobs.active {
		if !pointer.BoolDeref(job.Spec.Suspend, false) {
			job.Spec.Suspend = pointer.Bool(true)
			if err := r.Update(ctx, job); err != nil {
				return err
			}
		}
	}
	return r.ensureCondition(ctx, js, corev1.EventTypeNormal, metav1.Condition{
		Type:               string(jobset.JobSetSuspended),
		Status:             metav1.ConditionStatus(corev1.ConditionTrue),
		LastTransitionTime: metav1.Now(),
		Reason:             "SuspendedJobs",
		Message:            "jobset is suspended",
	})
}
```

That being said, I could see why we would want to replicate certain status fields from Jobs to Jobset such as StartTime.  I think you could grab these from the Job right now though.

**Comment by ahg-g** [comment]
For PodsReady, I guess you want a check on whether the JobSet was scheduled.

What about having a map of replicatedJobName to number of ready jobs in status? something like

```
type ReplicatedJobStatus struct {
  Name string
  ReadyJobs int
}

type JobSetStatus struct {
  // +listType=map
  // +listMapKey=name
  ReplicatedJobsStatus []ReplicatedJobStatus

  ...
}

```

**Comment by mcariatm** [comment]
> For PodsReady, I guess you want a check on whether the JobSet was scheduled.
> 
> What about having a map of replicatedJobName to number of ready jobs in status? something like
> 
> ```
> type ReplicatedJobStatus struct {
>   Name string
>   ReadyJobs int
> }
> 
> type JobSetStatus struct {
>   // +listType=map
>   // +listMapKey=name
>   ReplicatedJobsStatus []ReplicatedJobStatus
> 
>   ...
> }
> ```

I would use something like that, for easier addressing and updating them
````
type JobSetStatus struct {
  // +listType=map
  // +listMapKey=name
  ReplicatedJobsStatus map[job.Name]ReplicatedJobStatus

  ...
}
```



> Regarding `StartTime`, resetting it in Job was a hack to allow mutating scheduling directives; I guess JobSet can do that on suspend, so `ResetStatus` can probably just return false for the JobSet implementation.

Yes, make sense

**Comment by ahg-g** [comment]
> I would use something like that, for easier addressing and updating them

I see that we commonly use lists with listType=map, not using map directly in the apis. @alculquicondor any idea why?

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps

> The only exceptions are pure maps in the API (currently, labels, selectors, annotations, data), as opposed to sets of subobjects.

**Comment by kannon92** [comment]
Can we close this?

**Comment by mcariatm** [comment]
/close
Done #144 #143
