### ISSUE TITLE
Test grid should show all the tests successful or failure

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#137]
https://k8s-testgrid.appspot.com/sig-apps#pull-jobset-test-integration-main only shows a single row which is not ideal.

We enabled this in Kueue and it has helped identify flaky tests.

I think uploading junit reports for each test was all we needed for support in Kueue.

**Comment by kannon92** [comment]
https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-integration-main Is an example in Kueue.

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/kueue/pull/423 Approach for how I did this for Kueue

**Comment by clearnicki** [comment]
If this is still available - I'd like to work on this. 

/assign

**Comment by kannon92** [comment]
> If this is still available - I'd like to work on this.
> 
> /assign

Thanks for taking this! Please feel free to reach out to me if you have questions.

**Comment by clearnicki** [comment]
@kannon92 hey - thanks! I made PR #155 do you want to check it out?
