### ISSUE TITLE
Jobset status table

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#161]
**What would you like to be added**:

When you do kubectl get jobsets you only get a list of jobsets.  It’s be nice for this to be similar to a job at a minimum ie completions and/or failures. 

Maybe we can include how many replicated jobs have completed or failed? 

**Why is this needed**:

better debug ability

**Comment by ahg-g** [comment]
This should be doable using some kubebuilder tags: https://github.com/kubernetes-sigs/kueue/pull/156/files

do you want to take a stab at this @kannon92 ?

**Comment by kannon92** [comment]
I’ll be out of town the next couple weeks so I’ll leave it open.  I think with the recent changes for ReplicatedJobStatus this should be pretty accessible.

**Comment by A-Hilaly** [comment]
I'll take a quick stab at this if you haven't already @ahg-g :)
 
/assign

**Comment by ahg-g** [comment]
@A-Hilaly please go ahead! Welcome to the project :)

**Comment by A-Hilaly** [comment]
@ahg-g @kannon92 what do you think about adding `Completions`, `Failures` (similar to status.Restart) to JobSetStatus and make sure to update those during the reconciliation? We could add those as printcolumn tags.

**Comment by ahg-g** [comment]
Can we surface the replicatedjob status? https://github.com/kubernetes-sigs/jobset/blob/main/api/jobset/v1alpha1/jobset_types.go#L87-L89

**Comment by A-Hilaly** [comment]
Not sure i fully understand @ahg-g. The idea would be to add `Completions/Succeded` and `Failures` status fields to `JobSetStatus` and those will be calculated from replicatedJob status

**Comment by ahg-g** [comment]
I am not sure if there is a way to meaningfully calculate an aggregated status. I think users would expect a breakdown by replicatedJob

**Comment by A-Hilaly** [comment]
Makes sense! We can close this as it's not possible to show all the replicatedJob statuses in kubectl table response

**Comment by kannon92** [comment]
Thank you for leading this effort @A-Hilaly!!

/close
