### ISSUE TITLE
Add python and go client libraries

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#163]
**What would you like to be added**:

python and go client libraries

**Why is this needed**:

To be able to use the apis in code.

**Comment by ahg-g** [comment]
@tenzen-y can you advise how to do this?

**Comment by tenzen-y** [comment]
In go libraries, we can automatically generate by code-generator.

But, in Python libraries, I suggest implementing the client based on OpenAPI Schema.

**Comment by tenzen-y** [comment]
For example

training-operator: https://github.com/kubeflow/training-operator/blob/fc8a64464f364565fcd399d9d7724201e48b0dfa/sdk/python/kubeflow/training/api/training_client.py
katib: https://github.com/kubeflow/katib/blob/6e0069bc7eefe8b7b8a41bce7ea91219253da575/sdk/python/v1beta1/kubeflow/katib/api/katib_client.py

**Comment by ahg-g** [comment]
Thanks @tenzen-y 

> But, in Python libraries, I suggest implementing the client based on OpenAPI Schema.

Can you elaborate more? the examples you shared were written manually?!

**Comment by tenzen-y** [comment]
> Can you elaborate more? the examples you shared were written manually?!

Yes, manually...
Because we can not find to generate a client for Python from the API definition.
So, we manually implement based on open API schema generated from Golang Kubernetes API in the following step:

1. generate open API schema using k8s.io/openapi-gen
2. generate swagger file from openapi schema.
3. generate Python `model` from swagger file.
4. manually implement Python client.

**Comment by tenzen-y** [comment]
If there is any solution to auto-generate the Python client, I'd like to know that...

**Comment by kannon92** [comment]
Have we considered generating proto definitions from our CRD?  That would help you generate python bindings.  I know that k8 apis do generate proto from the go structs.

**Comment by tenzen-y** [comment]
We probably need to do step 4 even If we can generate protocol buffers definitions from our CRD.
IIUC, we can not generate a Python client from protocol buffer definition.

**Comment by tenzen-y** [comment]
The key here is there aren't tools to generate a Python client like https://github.com/kubernetes/code-generator.

**Comment by tenzen-y** [comment]
If we skip step 4, we can probably inform users to use [`CustomObjectsAPI`](https://github.com/kubernetes-client/python/blob/9a2d5e4290920225b528c84aa26d9305bdcc7baf/kubernetes/client/api/custom_objects_api.py#L27).

Honestly, `CustomObjectsAPI` is difficult to use...

**Comment by ahg-g** [comment]
> If we skip step 4, we can probably inform users to use [CustomObjectsAPI](https://github.com/kubernetes-client/python/blob/9a2d5e4290920225b528c84aa26d9305bdcc7baf/kubernetes/client/api/custom_objects_api.py#L27).

I didn't look at "CustomObjectAPI", so I am not sure what it does. But I know about the dynamic client, which should not be too complicated to use: https://github.com/kubernetes-client/python/tree/master/kubernetes/base/dynamic

**Comment by dannysheridan** [comment]
> If there is any solution to auto-generate the Python client, I'd like to know that...

Hey @tenzen-y I've run into this challenge before! That's why I started [Fern](https://buildwithfern.com/). You pass in your OpenAPI specification and get a Python client library that's published to PyPI.

**Comment by tenzen-y** [comment]
> I didn't look at "CustomObjectAPI", so I am not sure what it does. But I know about the dynamic client, which should not be too complicated to use: https://github.com/kubernetes-client/python/tree/master/kubernetes/base/dynamic

The dynamic client looks good. In the first step, we can inform users to use dynamic clients.

A multifunctional client such as training-operator can be provided if there are enough user requests.

So, currently, it is enough to provide dynamic clients.

**Comment by ahg-g** [comment]
Ok, for now, I think we can start by generating proto definitions and the python-equivalent APIs. The user can depend on dynamic client to interact with JobSet.

**Comment by danielvegamyhre** [comment]
I tried generating protos from the CRD using the Kubernetes [code-generator](https://github.com/kubernetes/code-generator) but ran into some issues, tried troubleshooting for a while without success. I detailed the issue and what I've tried in a question in the API Machinery Slack [here](https://kubernetes.slack.com/archives/C0EG7JC6T/p1685647927474879).

**Comment by tenzen-y** [comment]
@danielvegamyhre My PR on the Kueue side is probably helpful: https://github.com/kubernetes-sigs/kueue/pull/789

**Comment by danielvegamyhre** [comment]
@tenzen-y Thanks, I see your PR is generating a Go client, which is part of the goal of this issue, but what about the proto definitions that we will then use to generate the Python types to use with the Python dynamic client?

**Comment by tenzen-y** [comment]
@danielvegamyhre We (training-operator) generate openapi_generated.go by the openapi-gen.

https://github.com/kubeflow/training-operator/blob/1bb8da05bd0dc32f96095c3bfe82ee6adffc2d61/hack/update-codegen.sh#L99-L104

https://github.com/kubeflow/training-operator/blob/1bb8da05bd0dc32f96095c3bfe82ee6adffc2d61/pkg/apis/kubeflow.org/v1/openapi_generated.go

**Comment by tenzen-y** [comment]
Or, maybe we generate protocolbuffers definition using [go-to-protobuf](https://github.com/kubernetes/code-generator/tree/master/cmd/go-to-protobuf).

I haven't yet tried it.

**Comment by tenzen-y** [comment]
I tried to generate a proto with your command. And then, I faced the same error.

**Comment by tenzen-y** [comment]
Maybe, we need to preapre `SchemeBuilder` like the following:

https://github.com/kubernetes/kubernetes/blob/decf1e1a9b53a4f4b24bb780d6433e2d5e959d83/pkg/apis/apps/register.go#L26-L27

However, the `SchemeBuilder` conflicts with one generated by controller-runtime...

**Comment by danielvegamyhre** [comment]
@tenzen-y As a first step, I am trying to generate a client-go package following the example in your PR, however, all of the generated files are empty... https://github.com/kubernetes-sigs/jobset/pull/173 can you take a look when you have a moment and see if you notice anything wrong?

**Comment by tenzen-y** [comment]
> @tenzen-y As a first step, I am trying to generate a client-go package following the example in your PR, however, all of the generated files are empty... can you take a look at my [PR](https://github.com/kubernetes-sigs/jobset/pull/173) when you have a moment and see if you notice anything wrong?

Sure.

**Comment by danielvegamyhre** [comment]
@ahg-g Generated Go client is ready in #173 but someone in apimachinery slack said generating protos from custom resources is not supported, although they didn't seem 100% sure so I'll have to do some more research on that to see if that's accurate or not.
