### ISSUE TITLE
Scalability tests for exclusive Job to topology placement feature

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#174]
**What would you like to be added**:

Test the scalability of the exclusive Job to topology placement feature. Specifically, pod scheduling throughput at 5k node scale.

**Why is this needed**:

We use pod affinity and anti-affinity to implement exclusive 1:1 pod-to-node placement, which is known to be slow at scale. So this test is needed to understand scalability limits of this feature.

**Comment by danielvegamyhre** [comment]
**Summary**: I created a scalability/performance test of 250 indexed jobs with 15 pods each running on 5000 nodes and compared the scheduling throughput of this setup with pod affinities/anti-affinities configured for 1:1 job to topology domain assignment, versus no pod affinities configured.

Pod affinities/anti-affinities configured for 1:1 job to topology domain assignment result: 58 pods/second scheduling throughput.

Standard configuration (no pod affinities/anti-affinities) result: 266 pods/second scheduling throughput.
