### ISSUE TITLE
Existing jobs that are supposed to be created by jobset, but not owned by jobset

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#18]
Consider the case where the user creates a jobSet that is supposed to create a job with name x, but the job already exists and not owned by jobset, how should we reconcile this? here are a couple of options:

1) check if it the template matches the job spec and try to adopt it?
2) throw an event and status update on the jobset and suspend the jobset?

**Comment by ahg-g** [comment]
same question if the headless service already exists

**Comment by kannon92** [comment]
/assign

I'll start by adding some integration tests that reproduce this issue and then we can discuss what option we should do.  

I think 2 may be the best as I'm not sure we should force adopt other job/service.

**Comment by ahg-g** [comment]
The namespace is being deleted while the test is still trying to create a resource inside it.

**Comment by kannon92** [comment]
So currently, we do log an error in the jobset controller if a job exists.  

You can see this by looking at the logs of the jobset controller.  

Service, we do not do this.  

I have a PR just adding some test cases for this where we add a job and a service that exist.  Job you can see an error in the log and it fails to create.  Service will just work because of the following code:

```
func (r *JobSetReconciler) createHeadlessSvcIfNotExist(ctx context.Context, js *jobset.JobSet, rjob *jobset.ReplicatedJob) error {
	log := ctrl.LoggerFrom(ctx)

	// Check if service already exists. Service name is <jobSetName>-<replicatedJobName>.
	// If the service does not exist, create it.
	var headlessSvc corev1.Service
	subdomain := GenSubdomain(js, rjob)
	if err := r.Get(ctx, types.NamespacedName{Name: subdomain, Namespace: js.Namespace}, &headlessSvc); err != nil {
		headlessSvc := corev1.Service{
			ObjectMeta: metav1.ObjectMeta{
				Name:      subdomain,
				Namespace: js.Namespace,
			},
			Spec: corev1.ServiceSpec{
				ClusterIP: "None",
				Selector: map[string]string{
					jobset.JobSetNameKey:        js.Name,
					jobset.ReplicatedJobNameKey: rjob.Name,
				},
			},
		}
```
I think this overwrites the service and creates a new one.  I see some odd behavior here but no errors or warnings.

**Comment by danielvegamyhre** [comment]
While we've never encountered this edge case as far as I'm aware, I think we need to handle it for production readiness reasons. I think the simplest way to handle it would be to fail the jobset with a descriptive condition if there is an existing job with a namespaced name that conflicts with one of the child jobs we need to create for the JobSet.

@ahg-g @kannon92 what do you think?

**Comment by ahg-g** [comment]
Can we check what the statefulset controller does? it creates pods with specific names, so they kinda have the same issue.

**Comment by danielvegamyhre** [comment]
> Can we check what the statefulset controller does? it creates pods with specific names, so they kinda have the same issue.

If I'm looking at the right place, it seems the statefulset controller simply return an error if the pod it's attempting to create already exists: https://sourcegraph.com/github.com/kubernetes/kubernetes@7bb00356f06332e63a9f06acd42f1bdd8fc559d6/-/blob/pkg/controller/statefulset/stateful_pod_control.go?L121-126

**Comment by ahg-g** [comment]
ok, then I guess we are doing that already, and so we can close this
