### ISSUE TITLE
Add example using the Python SDK + Dynamic Client

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#189]
**What would you like to be added**:
An example script using the Python SDK + Dynamic client to interact with the JobSet API.

**Why is this needed**:
For users who use Python clients to interact with k8s to quickly and easily use the JobSet API.

Also to catch any bugs that may be present in the Python SDK that aren't caught by unit tests.

**Comment by kannon92** [comment]
I wanted to see if I could do this but it seems like there are a few issues with installing this as a package.  

I also notice a few things about this.  Do we really want to support python 2.7 and python3.3?  2.7 is way deprecated and same for python 3.3.  

I also notice that our setup.py doesn't seem to be close to functional for installing as a package.  

Can you also explain why we have gitlab.ci in the sdk code?  Not sure if K8 actually uses that config for CI?

**Comment by danielvegamyhre** [comment]
> I also notice a few things about this. Do we really want to support python 2.7 and python3.3? 2.7 is way deprecated and same for python 3.3.

These are the python versions used by the code generation tools (openapi code generator JAR). Maybe we need to update the JAR version being used if one is available: https://github.com/kubernetes-sigs/jobset/blob/main/hack/python-sdk/gen-sdk.sh#L26

> I also notice that our setup.py doesn't seem to be close to functional for installing as a package.

Can you explain what you mean? I was able to import and use `jobset` package in a Python script locally.

> Can you also explain why we have gitlab.ci in the sdk code? Not sure if K8 actually uses that config for CI?

It is auto-generated by the code generator tool mentioned above.

**Comment by kannon92** [comment]
So I would usually expect that I can install this as a python package into a virtual environment.  I usually avoid installing python code into global python as it always bits me in the butt over time.   

```
cd sdk/python
python3.10 -m venv ../test
source ../test/bin/activate
python3.10 -m pip install .
```
```
(python38) [ec2-user@ip-172-31-93-184 python]$ python3.10 -m pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/ec2-user/Work/GIT/jobset-kevin/sdk/python
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-k9xbp3j1
```

This is at least how I usually install python packages.  I created a python client for my Armada project (https://github.com/armadaproject/armada/tree/master/client/python) and we used pyproject.toml as a simple way to create an installable package.  In newer versions of python they have been trying to phase out setup.py.  So it could be worth switching to this with setuptools.

**Comment by ahg-g** [comment]
@kannon92 are you working on this? I think this is the only item that I think we should close for 0.2.0 release.

**Comment by kannon92** [comment]
I'm not sure I can commit to this if you want it done quick.  

It'd like to be able to install this sdk as a package and include it in a virtual environment.  I think there may be some cleanup needed to achieve that.  We could write an example not having that.

**Comment by kannon92** [comment]
I should also say that I have been trying to get my dev environment functional with these changes and I still have a few items I need to fix.  TIL Don't select amazon linux when building aws instances..  I have had a lifelife of hurt trying to figure out how to work around all of this..

**Comment by kannon92** [comment]
/assign

I took a stab at this and I made some changes to allow you to install the package.
