### ISSUE TITLE
Add namedspaced job name label 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#210]
**What would you like to be added**:

Add a namespaced job name label to pods and use that as the label selector for 1:1 exclusive placement.

**Why is this needed**:

The upstream job controller adds the `job-name` label, but it is not namespaced. This is a problem for the exclusive feature we have since job-name is not unique across namespaces.

@danielvegamyhre

**Comment by danielvegamyhre** [comment]
added this to requirements for v0.2.0
