### ISSUE TITLE
Multiple issues in JobSet CI

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#212]
CI system has been borked this week, making it difficult to get code checked in... repeatedly running into the following issues:
- failing to pull golang:1.20 image from GCR (seems like an intermittent prow or gcr issue that self-resolves but has been happening a lot lately. example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/211/pull-jobset-test-e2e-main-1-26/1674124616177553408)
- webhook connection refused (example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/209/pull-jobset-test-e2e-main-1-26/1674119214257934336)
- jobset object was modified, please retry with latest object" error (example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/211/pull-jobset-test-integration-main/1674124616152387584)
- "pod deleted unexpectedly" (never seen this one before - example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/209/pull-jobset-test-e2e-main-1-24/1674119214148882432)
- both e2e "pod ping tests" timeout

cc @ahg-g @kannon92

**Comment by tenzen-y** [comment]
Probably, https://github.com/kubernetes/test-infra/pull/29961 fixed the first issue.

**Comment by tenzen-y** [comment]
Regarding the second issue, adding logging to e2e like [kueue](https://github.com/kubernetes-sigs/kueue/blob/cc58315b5c572fd872e354bfafaea5582c04a60c/hack/e2e-test.sh) would be good And then we can investigate the root cause. I guess that the jobset controller takes a bit long time to start. So I believe that we need to increase resource requests in the e2e env.

**Comment by tenzen-y** [comment]
Regarding the third issue, it seems that we updated the jobset without getting created jobset after creating the jobset.
The issue is typically controller issue. So I would suggest getting jobset after https://github.com/kubernetes-sigs/jobset/blob/2903be85cb40273bff9bbaa19fb6b102d0db1d17/test/integration/controller/jobset_controller_test.go#L88.

**Comment by tenzen-y** [comment]
> > Regarding the second issue, adding logging to e2e like [kueue](https://github.com/kubernetes-sigs/kueue/blob/cc58315b5c572fd872e354bfafaea5582c04a60c/hack/e2e-test.sh) would be good And then we can investigate the root cause. I guess that the jobset controller takes a bit long time to start. So I believe that we need to increase resource requests in the e2e env.
> 
> Good idea, I just submitted [kubernetes/test-infra#29966](https://github.com/kubernetes/test-infra/pull/29966) to bump the CPU/memory resources to align with what Kueue presubmits use.

Also, adding `--wait` flag to kind would be helpful.

```diff
-$KIND create cluster --name $KIND_CLUSTER_NAME --image $E2E_KIND_VERSION
+$KIND create cluster --name $KIND_CLUSTER_NAME --image $E2E_KIND_VERSION --wait 1m
```

https://github.com/kubernetes-sigs/jobset/blob/main/hack/e2e-test.sh#L15

**Comment by danielvegamyhre** [comment]
> > > Regarding the second issue, adding logging to e2e like [kueue](https://github.com/kubernetes-sigs/kueue/blob/cc58315b5c572fd872e354bfafaea5582c04a60c/hack/e2e-test.sh) would be good And then we can investigate the root cause. I guess that the jobset controller takes a bit long time to start. So I believe that we need to increase resource requests in the e2e env.
> > 
> > 
> > Good idea, I just submitted [kubernetes/test-infra#29966](https://github.com/kubernetes/test-infra/pull/29966) to bump the CPU/memory resources to align with what Kueue presubmits use.
> 
> Also, adding `--wait` flag to kind would be helpful.
> 
> ```diff
> -$KIND create cluster --name $KIND_CLUSTER_NAME --image $E2E_KIND_VERSION
> +$KIND create cluster --name $KIND_CLUSTER_NAME --image $E2E_KIND_VERSION --wait 1m
> ```
> 
> https://github.com/kubernetes-sigs/jobset/blob/main/hack/e2e-test.sh#L15

Oh wow, I didn't know the kind cluster creation would finish/unblock before the control plane was ready... Just created https://github.com/kubernetes-sigs/jobset/pull/213 with your suggestion

**Comment by ahg-g** [comment]
> webhook connection refused (example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/209/pull-jobset-test-e2e-main-1-26/1674119214257934336)

May be we should use Eventually in the jobset create calls to wait for the jobset controller to come up: [here ](https://github.com/kubernetes-sigs/jobset/blob/main/test/e2e/e2e_test.go#L72) and [here](https://github.com/kubernetes-sigs/jobset/blob/main/test/e2e/e2e_test.go#L95)

**Comment by ahg-g** [comment]
Adding the logs would be great too, it will tell us why the jobset controller didn't get scheduled: https://github.com/kubernetes-sigs/kueue/blob/cc58315b5c572fd872e354bfafaea5582c04a60c/hack/e2e-test.sh#L27-L40

**Comment by ahg-g** [comment]
> jobset object was modified, please retry with latest object" error (example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/211/pull-jobset-test-integration-main/1674124616152387584)

For this one, [this update](https://github.com/kubernetes-sigs/jobset/blob/7534695e63d49cdb9893f5e38eecb210266c8719/test/integration/controller/jobset_controller_test.go#L103) needs to be wrapped in an Eventually clause with the following sequence:
1) js = client.Get(js.name)
2 update.fn(js)
3) client.Update(js)

similar to https://github.com/kubernetes-sigs/jobset/blob/7534695e63d49cdb9893f5e38eecb210266c8719/test/integration/controller/jobset_controller_test.go#L708

**Comment by tenzen-y** [comment]
> > jobset object was modified, please retry with latest object" error (example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/211/pull-jobset-test-integration-main/1674124616152387584)
> 
> For this one, [this update](https://github.com/kubernetes-sigs/jobset/blob/7534695e63d49cdb9893f5e38eecb210266c8719/test/integration/controller/jobset_controller_test.go#L103) needs to be wrapped in an Eventually clause with the following sequence:
> 
> 1. js = client.Get(js.name)
>    2 update.fn(js)
> 2. client.Update(js)
> 
> similar to
> 
> https://github.com/kubernetes-sigs/jobset/blob/7534695e63d49cdb9893f5e38eecb210266c8719/test/integration/controller/jobset_controller_test.go#L708

That's right.

**Comment by kannon92** [comment]
I'll open up a PR to make our e2e tests look similar to kueue (add logs) and I'll open up a PR to add eventually for updates as @ahg-g pointed out.

**Comment by ahg-g** [comment]
we addressed all issues mentioned here, right?

**Comment by danielvegamyhre** [comment]
> * "pod deleted unexpectedly" (never seen this one before - example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/209/pull-jobset-test-e2e-main-1-24/1674119214148882432)

Yes, everything except the "pod deleted unexpectedly" (example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/209/pull-jobset-test-e2e-main-1-24/1674119214148882432) but that appears to have been a transient issue or perhaps was fixed by bumping the CPU/memory resources for the e2e tests.  We can close this now.
