### ISSUE TITLE
API integer types should have explicit size (int32, int64)

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/jobset#218]
This should be `int32` https://github.com/kubernetes-sigs/jobset/blob/b69dd6aad5375ef191e780d35b883fbcb9142656/api/jobset/v1alpha2/jobset_types.go#L124

Given the validation that it's already in place, I think it should be safe to change the type.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types

**Comment by kannon92** [comment]
/assign 

I'll take a stab at this.
