### ISSUE TITLE
Publish JobSet in GCR

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#22]
We should publish the latest version and then for each release.

**Comment by ahg-g** [comment]
see example: https://github.com/kubernetes-sigs/kueue/issues/52

**Comment by danielvegamyhre** [comment]
This is now complete. See [gcr.io/k8s-staging-jobset](https://gcr.io/k8s-staging-jobset) where I've published an initial image built from `main`. The prod artifacts repos ([example](us.gcr.io/k8s-artifacts-prod/jobset)) are created but will be empty until we promote an image from staging to prod when cut our first release.
