### ISSUE TITLE
Generate client-go/sdk only if api changed.

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#222]
Running unit tests/integration tests will now require regeneration of client-go/sdk every time.  I think we should try to make this a bit smarter as it does make unit or integration tests take a lot longer.  

I see two options for development:

1) Only build client-go/sdk if the api was changed. 
2) Move building of client-go/sdk into a separate target and call it separately from `make` or `make test` or `make test-integration`.  

Currently it is built alongside `make` so it will run on every build.

**Comment by danielvegamyhre** [comment]
+1 on this

**Comment by kannon92** [comment]
@danielvegamyhre which preference would you have for this? 

I can see benefits of logic to detect changes being useful but I also wonder if making the client generation explicit and just detecting that api is different would be less brittle and having a check to see if api mismatches and just telling the user they need to run generate step..

**Comment by danielvegamyhre** [comment]
Yeah I think option 2 would be the most straight forward. We could make the change detection part of the verify step in the CI.

**Comment by A-Hilaly** [comment]
I'd like to give to this one a shot :)
/assign
