### ISSUE TITLE
☂️ Requirements for v0.3.0 release

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#239]
Deadline November 1st. We are still gathering requirements for v0.3.0, please feel free to comment suggestions.

Must have:
- [x] https://github.com/kubernetes-sigs/jobset/issues/310
- [x] https://github.com/kubernetes-sigs/jobset/issues/174
- [x] https://github.com/kubernetes-sigs/jobset/issues/341
- [x] #263
- [x] https://github.com/kubernetes-sigs/jobset/issues/277
- [x] #283 

Nice to have:
- [ ] #262 
- [ ] #104 
- [x] https://github.com/kubernetes-sigs/jobset/issues/78
- [ ] https://github.com/kubernetes-sigs/jobset/issues/146
- [ ] https://github.com/kubernetes-sigs/jobset/issues/77
- [x] https://github.com/kubernetes-sigs/jobset/issues/130

**Comment by kannon92** [comment]
Considering the light "Must-Haves", what do you and @ahg-g think about a strech-goal of including https://github.com/kubernetes-sigs/jobset/issues/104?

I know there is some questions around it but it will keep us honest if we put it on our release.  IMO I also think it will be a really useful feature for JobSet users.  /cc @vsoch @Gekko0114

**Comment by ahg-g** [comment]
Sounds good to me if you have a proposal.

**Comment by kannon92** [comment]
> Sounds good to me if you have a proposal.

I drafted a KEP for [it](https://github.com/kubernetes-sigs/jobset/pull/244).

**Comment by kannon92** [comment]
Not sure if you all have promoted this somewhere but I'd be nice to target a blog post or an announcement with maybe this release.  

I was thinking something around the level of https://kubernetes.io/blog/2022/10/04/introducing-kueue/

**Comment by vsoch** [comment]
I'd be in support! I'm definitely enjoying using Jobset - it's the basis of my new operator: https://converged-computing.github.io/metrics-operator/getting_started/metrics.html :partying_face:

**Comment by danielvegamyhre** [comment]
Added #104, #262, #263 to must-haves. We can revisit laster

**Comment by danielvegamyhre** [comment]
Release v0.3.0 has been published. I'll move the outstanding issues to v0.4.0
