### ISSUE TITLE
Question:  Do you plan to create a pipeline of Jobs?

### ISSUE THREAD

**Issue by Gekko0114** [kubernetes-sigs/jobset#240]
Thank you for the development of this interesting OSS.
I have a question.

I think it would be very reasonable to develop `JobSet` to meet the needs of AI/ML workloads. On the other hand, in ML pipelines, it is often required to run multiple Jobs sequentially, such as running Job A, then Job B, and then Job C after that.
Can `JobSet` cover this functionality of executing Jobs in sequence, or should features like these be handled by another OSS like `Argo`?

**Comment by kannon92** [comment]
We have this issue/feature. https://github.com/kubernetes-sigs/jobset/issues/104

**Comment by Gekko0114** [comment]
I thought this feature was only about supporting which one to start first, the worker or the driver.
Does it also cover running multiple Jobs sequentially, like Job A -> Job B -> Job C -> ....?

**Comment by danielvegamyhre** [comment]
> I thought this feature was only about supporting which one to start first, the worker or the driver. Does it also cover running multiple Jobs sequentially, like Job A -> Job B -> Job C -> ....?

That's correct, the idea described in #104 would only address things like the leader/work pattern, where we wait to start the worker until the leader (Job A) is running before starting the worker (Job B) - that is, not waiting until Job A is **finished** but waiting until Job A is **ready**. 

However, I think the proposed design could easily be extended to include an extra knob to configure if we want to wait until the previous Job is **ready** or until it is **finished** before starting the next job.

**Comment by Gekko0114** [comment]
> However, I think the proposed design could easily be extended to include an extra knob to configure if we want to wait until the previous Job is ready or until it is finished before starting the next job.

I see. Sounds useful. Thank you for your explanation!

**Comment by kannon92** [comment]
> > I thought this feature was only about supporting which one to start first, the worker or the driver. Does it also cover running multiple Jobs sequentially, like Job A -> Job B -> Job C -> ....?
> 
> That's correct, the idea described in #104 would only address things like the leader/work pattern, where we wait to start the worker until the leader (Job A) is running before starting the worker (Job B) - that is, not waiting until Job A is **finished** but waiting until Job A is **ready** before launching Job B.
> 
> However, I think the proposed design could easily be extended to include an extra knob to configure if we want to wait until the previous Job is **ready** or until it is **finished** before starting the next job.
> 
> Building off of @kannon92's comment, maybe something like this:
> 
> ```
> type StartupPolicy struct {
> 	// Operator determines either All or Any of the selected jobs should be ready to 
>         // consider the replicatedjob ready.
> 	// +kubebuilder:validation:Enum=All;Any
> 	Operator Operator `json:"operator"`
> 
> 	// TargetReplicatedJobs are the names of the replicated jobs the operator will apply to.
> 	// A null or empty list will apply to all replicatedJobs.
> 	TargetReplicatedJobs []string `json:"targetReplicatedJobs,omitempty"`
> 	
> 	// Condition defines what condition the previous job should be in before starting
>         // the next job (ready or finished).
>         // +kubebuilder:validation:Enum=Ready;Finished
>         Condition JobCondition `json:"condition"`
> }
> ```

Only issue with `ready` is that we don't yet have a condition in Jobs to say when a job is ready (https://github.com/kubernetes/kubernetes/issues/117758).

**Comment by kannon92** [comment]
Based on a discussion with @ahg-g and @danielvegamyhre in the startup policy KEP, I don't know if we will cover a pipeline of jobs (ie sequential completed execution).

**Comment by danielvegamyhre** [comment]
As @kannon92 mentioned above, after some discussion we concluded we want to keep the startup policy API simple and specific to sequential **startup**, to address specific requirements of distributed training frameworks. For now, we do not want to expand to include other use cases, like sequential completed execution, where the API can quickly explode into a full blown workload DAG / workflow execution engine.
