### ISSUE TITLE
Completions == 1 impossible for indexed job > 1 parallelism

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/jobset#241]
I'm creating an indexed job, and I'd like to say it is successful when there is one completion. Reading about completion mode here: https://kubernetes.io/docs/concepts/workloads/controllers/job/#completion-mode I'm not allowed to put 1, because it will default to one parallelism. Here are my options (none work):

- Setting explicitly to 1 sets parallelism to 1, which I don't want
- If I leave completions unset, which should mean 1, I get the error below

```console
 {"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"metricset-sample","namespace":"default"}, "namespace": "default", "name": "metricset-sample", "reconcileID": "6f738a8c-fdc8-4adb-ac09-fc917fc399f2", "error": "Job.batch \"metricset-sample-m-0\" is invalid: spec.completions: Required value: when completion mode is Indexed"}
```
The use case is an mpirun application that is running from one pod, and the rest (ideally) I could let sleep until the job completes (indicated by the mpirun command completing). Why is it impossible to run an indexed job with parallelism > 1 but not indicate one job finishing is criteria for the job finishing?

There is likely an issue / PR open to fix this, but I'm wondering what the workaround it (and why the logic was decided this way?)

**Comment by ahg-g** [comment]
I would discuss this in upstream k8s since it is about indexed job semantics. But in general, indexed job depends on completions to define the range of indexes, that is why it is mandatory, we discussed briefly using parallelism when completions is not set, but it was dismissed.

As for the mpi use case, why not define two jobs using JobSet, one of size 1 for the driver and one for the workers. Using success policy, you can define that the JobSet is successful and complete when the driver is.

**Comment by vsoch** [comment]
> As for the mpi use case, why not define two jobs using JobSet, one of size 1 for the driver and one for the workers. Using success policy, you can define that the JobSet is successful and complete when the driver is.

This did cross my mind! I think it's a good idea, and I haven't tried it yet because it affords updating the design of my operator. But I think I will - I'll update this issue after, and then decide if it makes sense to discuss upstream. Will report back (hopefully) soon!

**Comment by kannon92** [comment]
> > As for the mpi use case, why not define two jobs using JobSet, one of size 1 for the driver and one for the workers. Using success policy, you can define that the JobSet is successful and complete when the driver is.
> 
> This did cross my mind! I think it's a good idea, and I haven't tried it yet because it affords updating the design of my operator. But I think I will - I'll update this issue after, and then decide if it makes sense to discuss upstream. Will report back (hopefully) soon!

You reminded me that I got this working to help demonstrate a useful case for JobSet.  I decided to add an example to for this usecase as I can see it being useful: https://github.com/kubernetes-sigs/jobset/pull/243

**Comment by vsoch** [comment]
Thank you!

**Comment by vsoch** [comment]
okay - refactor done!

This took me a few days, but I think it's a better direction. To step back, I'm working on a metrics operator that is going to help us understand things like application / storage performance. My goal is to use JobSet as the packaging means for a number of different kinds of Metric Sets. You can think of a MetricSet akin to a JobSet, but for different kinds of metrics, and the operator understands three kinds of MetricSets

- An Application Metric set measures application performance (for one or more metrics)
- A Storage Metric Set measures the same for storage (volumes)
- A Standalone Metric Set can have a metric that does whatever it wants (e.g., the networking example above)

So when I was working on the third of those bullets, a custom networking metric that has a launcher/worker setup (and I couldn't get the workers to complete) I realized I wasn't using JobSet to its maximum potential (but I opened this issue just to double check there was no way). I chewed on this design for a bit because I wanted to design it in a way that the user experience is simple and consistent - they write a simple metrics.yaml file with some listing of metrics, and they have similar structure. But on the backend of the operator, it understands the three concepts above.

![image](https://github.com/kubernetes-sigs/jobset/assets/814322/c5aee27a-9350-4527-a296-b1ed24b73830)

In the example above, we see a user requesting two metrics alongside their application, which the operator will validate, and then prepare a Jobset for. Since it's an application Metric Set, this means a JobSet with a single job and the application container with the metrics as sidecars. The user doesn't need to make any changes to their container because of the shared process namespace - that's the trick of this kind of MetricSet - monitoring the processes in sidecar containers by finding the PID based on the command. A Storage Metric set wouldn't use this shared process namespace, but instead would ensure each storage metric container has the volume mounted.

Anyway - that's the WIP so far! More diagrams and details are here: https://converged-computing.github.io/metrics-operator/getting_started/user-guide.html. I'm hoping to next add more actual metrics for storage, think about a better means to collect the output, and then hopefully actually run experiments! If I'm successful this would be a cool demonstration of using JobSet (sort of?) meaningfully for experiments. Otherwise, I've just been having fun this week (I guess that is OK too!)

Thanks for the help! I'm going to close the issue.
