### ISSUE TITLE
Headless service should use fully qualified job label name.

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#26]
https://github.com/kubernetes-sigs/jobset/blob/main/pkg/controllers/jobset_controller.go#L244

```
					// TODO: Migrate to the fully qualified label name.
					"job-name": job.Name,
```

Generally, we should use names that are fully qualified for labels.

Not sure if that means we should reject JobSpec names that aren't valid label names.

**Comment by ahg-g** [comment]
> Not sure if that means we should reject JobSpec names that aren't valid label names.

This is not something jobset or any workload controller is responsible for enforcing. Can be discussed in upstream k8s, although I don't expect this change since it is not backward compatible.

**Comment by kannon92** [comment]
I guess I don’t understand the TODO in the code then.  Wouldn’t you want the service name to be based on a dns allowed name for names?

**Comment by ahg-g** [comment]
The TODO is referring to the label key in the service label selector, it is about using the fully qualified name ["batch.kubernetes.io/job-name"](https://github.com/kubernetes/kubernetes/blob/d97ea0f705847f90740cac3bc3dd8f6a4026d0b5/pkg/apis/batch/types.go#L44) instead of the legacy one ["job-name"](https://github.com/kubernetes/kubernetes/blob/d97ea0f705847f90740cac3bc3dd8f6a4026d0b5/pkg/apis/batch/types.go#L41). 

The issue is that the fully qualified name is new and not supported on older k8s releases.

**Comment by kannon92** [comment]
Ah. I see! Thanks for clearing that up!

**Comment by kannon92** [comment]
Do you have a target for job set on kubernetes releases?  We could just go forward and say it’s supported only on the latest (1.27)? Or do we want to aim to support n-2?

**Comment by ahg-g** [comment]
We would like to be able to use it on older k8s releases, most cloud providers are still on older versions, so we need to support at least 1.25, so yeah n-2 seems reasonable. I think in the future we will likely release in tandem with k8s releases

**Comment by kannon92** [comment]
/priority important-longterm

From what @ahg-g said, we could migrate to using the fully qualified name but we run into backwards capability if we directly used the label that is available in the batch API.  The labels are defined here in k/k: https://github.com/kubernetes/kubernetes/blob/e8108b5a47c0923188c7fe8f55986daabcf01b9b/staging/src/k8s.io/api/batch/v1/types.go#L25

I think this can be considered a long term minor fix?

**Comment by danielvegamyhre** [comment]
@kannon92 do you think this is still necessary? I have no strong feelings on this one, I am going through our backlog of issues and trying to clean up any stale ones. Let me know if you think this is still important to pursue, otherwise I will close it after some time.

**Comment by kannon92** [comment]
I think so. The non k8s prefixed label is depreacted so we should switch to use the new label.

But we need it to be in all supported versions of k8s for JobSet. So I think we may have one more release. 

AFAIK that label was put into kube for 1.27. So once 1.26 is no longer supported I think all releases should have this label.

**Comment by ahg-g** [comment]
Can we check if the canonical one exists and use it, otherwise fall to the old one.

**Comment by kannon92** [comment]
@googs1025

would you want to try this one? The last suggestion is worth exploring.

**Comment by kannon92** [comment]
Actually we dropped 1.26 so I think we could just use the official label now.

**Comment by googs1025** [comment]
@kannon92 Thanks for your invitation. It sounds good, but I want to solve the PR of the unit test first, and then participate in this issue.
