### ISSUE TITLE
Bug: unable to setup indexes  

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#263]
Users are reporting an issue when they apply their JobSet, the JobSet object is created but it never starts running. After examining the logs we found the following error:

```
2023-08-22T21:19:59Z    ERROR    Reconciler error    {"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", ....  "error": "Index with name field:.metadata.controller does not exist"}
```

The index on `.metadata.controller` is created in [SetupIndexes](https://github.com/kubernetes-sigs/jobset/blob/main/pkg/controllers/jobset_controller.go#L179) which is called from main.go [here](https://github.com/kubernetes-sigs/jobset/blob/main/main.go#L100). If the indexes cannot be built, we would expect to see [this error logged](https://github.com/kubernetes-sigs/jobset/blob/main/main.go#L101). Looking further in the logs, we do indeed see this error:

```
2023-08-21T14:37:20Z    ERROR    setup    unable to setup indexes    {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: batch/v1: Get \"https://10.72.0.1:443/apis/batch/v1\": dial tcp 10.72.0.1:443: i/o timeout"}
```

/kind bug

**Comment by danielvegamyhre** [comment]
Perhaps adding retry logic with some kind of exponential backoff policy [here](https://github.com/kubernetes-sigs/jobset/blob/main/main.go#L100) would be sufficient

**Comment by danielvegamyhre** [comment]
@kannon92 I notice Kueue has a helper `utilruntime.Must(...)` in which they call SetupIndexes. Perhaps we should implement something similar? This bug has been popping up a lot lately so I want to fix it asap.

**Comment by kannon92** [comment]
Yea I think that is a good idea.

**Comment by alculquicondor** [comment]
Interesting. I wouldn't have expected `SetupIndexes` to fail.
For whatever reason, we haven't hit these issues. From the message, it looks like the apiserver was down.

Indeed it seems best to exit.

**Comment by vsoch** [comment]
Correct - I've seen this several times, usually when I install / uninstall something and the only fix is to delete and re-create the entire cluster.
