### ISSUE TITLE
Handle service name exceeds max length error gracefully

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#277]
**Current behavior:**

When the jobset controller generates service names, it's possible they will exceed the 63 character length limit, resulting in an error when attempting to create the service. The Reconcile() call encounters this error and returns early before doing anything useful, so at this point the controller is effectively blocked from reconciling all jobsets it owned (i.e. no jobs being created, no pods being scheduled, etc.)

**Desired behavior**:
Can we find a way to log the error and not reconcile the misconfigured jobset, but continue reconciling any other jobsets?

**Comment by danielvegamyhre** [comment]
cc @kannon92 curious to get your thoughts on this. It seems like a separate Reconcile() call would occur for each jobset, so the controller would be able to continue to reconcile valid jobsets even if there was one hitting this service creation error, but today I observed a case where no jobset jobs or pods were getting created for any jobset until we deleted the jobset with the service name that was too long.

**Comment by kannon92** [comment]
My 2cents would be to validate this on creation if possible.  

Service names must follow this so we probably should be validating.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names
