### ISSUE TITLE
Predictible hostnames with one replicated job

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/jobset#290]
I'm testing a JobSet with just one replicated job, and one pod.  The predictable hostname has gone away. E.g., what i'd want is:

```bash
# Either of the following would work
metricset-sample-l-0.ms.default.svc.cluster.local
metricset-sample-l-0-0.ms.default.svc.cluster.local
```

But in practice I get:

```bash
metricset-sample-l-0-qcnd9.ms.default.svc.cluster.local
```

The addition of the pod random mangled string makes it impossible to predict and thus write applications for. Given that someone has chosen to use JobSet, it would be useful to have consistent behavior, even if there is just one replicated job and one pod. What do others think?

**Comment by kannon92** [comment]
What do you mean by has gone away? Was this working in a previous release and has stopped working?

what Jobset spec are you using?

I think you should write applications based on labels selectors rather than relying on specific names.

**Comment by vsoch** [comment]
> What do you mean by has gone away?

I mean as in the example above. When I have two replicated jobs, I get a predictable string. When I have just one, and one pod, I get the addition of the pod name `qcnd9`.

**Comment by danielvegamyhre** [comment]
/kind bug

Can you describe the job and check if it's in indexed completion mode?

**Comment by vsoch** [comment]
> Can you describe the job and check if it's in indexed completion mode? I will try to reproduce this as well. Can you paste an example JobSet yaml?

You know what, I think that's obviously it - this is a user error I think, I forgot that I had that logic. Sorry for the noise!

**Comment by danielvegamyhre** [comment]
Ah ok, np!
