### ISSUE TITLE
Document fungible jobs with JobSet

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/jobset#294]
**What would you like to be added**:

Can we have a list of jobs can be replaced by jobset in the homepage, e.g. `README.md`,  kind for new comers to know more about the project.

**Why is this needed**:

Kind to new comers.

**Comment by kannon92** [comment]
What do you mean by supported jobs?

**Comment by kerthcet** [comment]
Oh sorry I mean what kind of job can be replaced by jobset now, like MPIJob?

**Comment by kannon92** [comment]
I see.

So we have docs on how to run Pytorch jobs and I have a PR up to add a way to run Tensorflow.  

There is an issue to support MPI Jobs but the main issue is on how to generate the environment variables.  

https://github.com/kubernetes-sigs/jobset/pull/253

and MPI issue: https://github.com/kubernetes-sigs/jobset/issues/146

**Comment by kerthcet** [comment]
Close as we have some examples at https://github.com/kubernetes-sigs/jobset/blob/main/docs/tasks/README.md

/close
