### ISSUE TITLE
CronJobSet

### ISSUE THREAD

**Issue by MaGaroo** [kubernetes-sigs/jobset#295]
**What would you like to be added**:
I think it's good to be able to create new jobsets periodically like the way cronjob creates new jobs periodically.

**Why is this needed**:
The exact same reason why cronjob resource was needed in k8s.

**Comment by danielvegamyhre** [comment]
Hmm, so the use case you have in mind is periodically re-training a model on updated data? Can you give example use cases?

**Comment by MaGaroo** [comment]
It's interesting to me that the development team has a bias toward machine learning use cases. :grinning: 
But yes, my use case is similar to what you mentioned. There is some data that must be processed in a manner (that jobset handles well, but is a bit tricky to handle using the simple batch/job resource) regularly.

**Comment by danielvegamyhre** [comment]
Personally I think this would complicate the API and perhaps require an entire new CRD + operator, and it is beyond the scope of JobSet. I think periodically rerunning a workload on a daily/weekly/etc basis is best handled by some external software, not the workload controller itself. 

@kannon92 @ahg-g if you disagree feel free to comment, otherwise I will close this soon.

**Comment by kannon92** [comment]
I think it should require a new CRD + operator. Its similar to how we have both a Job and a CronJob in k8s. 

CronJob essentially handles scheduling and creates the Job.

I think if someone is interested they could wrap JobSet into a new CRD called a CronJobSet.

**Comment by danielvegamyhre** [comment]
Yeah, agreed, similar to Job and CronJob. This is beyond the scope of JobSet so I am going to close this issue, but thanks for the suggestion @MaGaroo and if you end up implementing a CronJobSet do let us know, I'd be very interested to see it!

**Comment by Rx-11** [comment]
I have a simple implementation of this, do check it out. [k8s-CronJobSet](https://github.com/Rx-11/k8s-CronJobSet)
