### ISSUE TITLE
Declare dependency relation between the jobs in a jobset

### ISSUE THREAD

**Issue by MaGaroo** [kubernetes-sigs/jobset#296]
**What would you like to be added**:
I would like to declare dependency between the jobs in my jobsets.

**Why is this needed**:
This feature lets us run a bunch of dependent jobs efficiently according to their dependency DAG.
Also, the name of the project already implies it should handle this use case. (Actually, it's the reason I encountered this project :grinning:)

**Comment by kannon92** [comment]
We have this issue: https://github.com/kubernetes-sigs/jobset/issues/104 

this for simple cases like starting in order or which jobs to start first. More complicated syntax should probably utilize a workflow language like CWL, Airflow or Argo. 

And I have a proposal for it but we explicitly call out that we won’t support dags like syntax.

**Comment by MaGaroo** [comment]
Oh okay.
Just curious to know, is there a roadmap or proposal for this project written anywhere so I can read it/them?

**Comment by danielvegamyhre** [comment]
@magaroo We discussed the possibility of supporting more complex dependency relations between jobs as part of the Startup Policy API discussion (#244) but ultimately decided against it. We will support some limited dependency relations (sequential startup), as it is a requirement for some popular distributed training frameworks, and we want JobSet to stay focused on its primary use case of modeling a single distributed ML/HPC workload, and not expand the scope to include managing workload DAGs / workflow execution management.
