### ISSUE TITLE
What would cause field:.metadata.controller does not exist?

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/jobset#325]
I'm testing an operator that uses JobSet, and every once in a while I see my CRDs stop creating, and the error is in the JobSet log, specifically:

```console
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226
2023-11-04T03:12:30Z    ERROR   Reconciler error        {"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"metricset-sample","namespace":"default"}, "namespace": "default", "name": "metricset-sample", "reconcileID": "cfc44b3d-f541-422f-a589-97d6fedce45c", "error": "Index with name field:.metadata.controller does not exist"}
```

This isn't urgent (non blocking, because I can delete the entire cluster and start fresh) but I'd like to understand what causes the index with name field: metadata.controller to not exist, and how to either avoid or fix it. Thank you!

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/jobset/tree/main/docs/faq#2-jobset-is-created-but-child-jobs-andor-pods-are-not-being-created

**Comment by kannon92** [comment]
More details here: https://github.com/kubernetes-sigs/jobset/issues/263

**Comment by vsoch** [comment]
I was using 0.2.0 - so I'll bump up to 0.2.1. Thanks @kannon92 ! Also I didn't know you moved over to RedHat from G-Research? Congrats!

**Comment by kannon92** [comment]
Thank you!

/close
