### ISSUE TITLE
E2E tests seem to fail quite often.

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#346]
We should have stable tests in our CI.

https://testgrid.k8s.io/sig-apps displays the jobset tests and our e2e tests are considered flaky.

The most common failure is related to the webhook not being ready. Looks like we wait for 600 s and fail. We could maybe have a smarter way to detect this.

**Comment by kannon92** [comment]
@tenzen-y or @alculquicondor any ideas on how to make the e2e tests more stable? I don't think the Kueue ones have this issue and we have similar code..

**Comment by alculquicondor** [comment]
Interesting.... Our suite attempts to create a ResourceFlavor object until it succeeds. But the timeout is just 1 minute.

At some point, we were facing lots of issues, but we solved them by increasing the CPU and memory requests for the e2e jobs. https://github.com/kubernetes/test-infra/pull/29948

**Comment by kannon92** [comment]
Notice that Kueue seems to also have some issues with this: https://github.com/kubernetes-sigs/kueue/issues/1372

Looks like @danielvegamyhre just merged a change to bump cpu/memory requests for those tests so we will see if this helps in our case.

**Comment by tenzen-y** [comment]
@kannon92 Following the Grafana dashboard might be helpful.

https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&from=now-7d&to=now&var-org=kubernetes-sigs&var-repo=jobset&var-job=pull-jobset-test-e2e-main-1-28&var-build=All&refresh=30s

**Comment by kannon92** [comment]
Looking at that @tenzen-y idk if that would be the reason why we are seeing failures..

**Comment by danielvegamyhre** [comment]
Yeah this is confusing to me, I bumped the timeout to 10min and bumped our CPU/memory resources for the e2e tests and we still timeout sometimes.

**Comment by alculquicondor** [comment]
we are definitely seeing a lot of failures in the past 2 weeks, whereas before we didn't find any problems.
Maybe worth checking with SIG kubernetes infra whether there was a change?

**Comment by danielvegamyhre** [comment]
This seems to be resolved, so I think it was a transient test infrastructure issue.
