### ISSUE TITLE
Having issue with importing as go module

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/jobset#353]
I was previously using v1alpha1 for a package, and updated to:

```
sigs.k8s.io/jobset/api/v1alpha2
```
And even when I try (the fix I used last time):

```
$ go get -u sigs.k8s.io/jobset/api/v1alpha2@05acd930c229190b2494a05a04bcc77b001b7814
go: downloading sigs.k8s.io/jobset v0.3.0
go: module sigs.k8s.io/jobset@05acd930c229190b2494a05a04bcc77b001b7814 found (v0.3.0), but does not contain package sigs.k8s.io/jobset/api/v1alpha2
```
That doesn't seem to work, regardless of the approach (go mod cache clean, go mod tidy/vendor, etc). For curiosity I went to the address, https://github.com/kubernetes-sigs/jobset/blob/main/api/v1alpha2

and it redirected that the branch wasn't found. Maybe the redirect to get to here is pointing to an old branch (master?) 

![image](https://github.com/kubernetes-sigs/jobset/assets/814322/9dab0b58-e2f1-4c84-9184-d83e799d547a)

Would be great to get these fixed - I'm updating a few old operators for further work with jobset. Thank you!

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/jobset/blob/main/api/v1alpha2 -> https://github.com/kubernetes-sigs/jobset/tree/main/api/jobset/v1alpha2

It seems to not have changed from release 0.2.0 to 0.3.0 so not sure why its different.

**Comment by vsoch** [comment]
I was using a 0.1.x variant for this one I'm trying to update. I had similar trouble with going from that to 0.2.0 for another project but the method to add via the commit worked (it didn't this time).

**Comment by vsoch** [comment]
okay I figured this out.

When you are making your package, you can't put the full path to start. I deleted my go.sum, and then changed all my jobset imports as follows:

```
- "sigs.k8s.io/jobset/api/jobset/v1alpha2"
+ "sigs.k8s.io/jobset"
```
And then do go mod tidy, go mod vendor, and that will find the right package and update the module files. Then you can tweak the actual paths and it will work.

Thanks @kannon92 this has bit me twice now and I think the above is the answer. It's something weird with how the redirect link works (if you just use a GitHub alias it would work fine, but the special naming here and need to match with the name in go.mod makes that not work). Hopefully this helps someone in the future.

Closing!
