### ISSUE TITLE
Add managed-by label similar to the proposed on in Job

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#379]
**What would you like to be added**:
A managed-by label to follow up on https://github.com/kubernetes/enhancements/pull/4370

**Why is this needed**:
MultiKueue support

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/jobset/pull/407 
/assign @trasc

**Comment by trasc** [comment]
/close 
#407 is now merged
