### ISSUE TITLE
Update JobSet condition in place if it exists.

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#39]
We should update JobSet condition in place if it exists, rather than always appending a new condition.

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/jobset/pull/20

I implemented this somewhat in the above PR.  May be useful if you take it.

im in Kubecon this week but I could take it next week

**Comment by kannon92** [comment]
I think we can close this since #20 merged.  

/close
