### ISSUE TITLE
JobSet website + docs

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#401]
**What would you like to be added**:
A polished website + docs, similar to what Kueue has: https://kueue.sigs.k8s.io/

**Why is this needed**:
We are graduating JobSet to v1 (#380) and we need polished, detailed docs that are commensurate with its level of maturity and production-readiness.

**Comment by moficodes** [comment]
Request for Netlify: https://github.com/kubernetes/org/issues/4748
Request for CNAME entry: https://github.com/kubernetes/k8s.io/pull/6406
Request for Logo: https://github.com/kubernetes/steering/issues/279

**Comment by kannon92** [comment]
@moficodes and @danielvegamyhre can we get an update on this issue?

**Comment by kannon92** [comment]
@danielvegamyhre can you add a link to the https://jobset.sigs.k8s.io/ in our project description page?

I'd add it but I don't think I can.

**Comment by danielvegamyhre** [comment]
The last thing we are waiting on here is the JobSet logo I believe.

**Comment by danielvegamyhre** [comment]
> https://jobset.sigs.k8s.io/

Sorry what project description page are you referring to?

**Comment by kannon92** [comment]
On the github main site. top right. Look at Kueue. It links to the jobset website.

We don't have any mention of the jobset site.

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/kueue

**Comment by danielvegamyhre** [comment]
> On the github main site. top right. Look at Kueue. It links to the Kueue website.
> 
> We don't have any mention of the jobset site.

Gotcha, added, thanks!

**Comment by kannon92** [comment]
@danielvegamyhre should we move this out of the must haves for release v0.5.0? We are waiting on a logo but the code for the website seems there. We even link to it.
