### ISSUE TITLE
JobSet v0.3.2 patch release

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#413]
Fixes to be included in patch release:
- [X] #403 
- [x] #393 
- [x] #395 
- [x] #404 
- [x] #409

**Comment by kannon92** [comment]
Maybe we need to add https://github.com/kubernetes-sigs/jobset/pull/403 also

**Comment by danielvegamyhre** [comment]
> Maybe we need to add #403 also
> 
> The PRs are all failing for the same reason. So thinking this PR could help get the CI pass again.

Good catch, thanks! Will cherry pick that one first.

**Comment by danielvegamyhre** [comment]
Manually tested release-0.3 branch with cherry picks and confirmed things work as expected:

- foreground deletion results in faster failure recovery time
- validation in #409 work

Before making the patch release, I am tempted to add some conditional logic to the validation logic added in #409, to return a custom, clear error if the generated pod name is longer than 63 chars, rather than the default error message (i.e., if the error returned by "IsDNS1035Label" contains "must be no more than 63 characters" then return a custom error message, otherwise return the error returned by the validation function).

Current error message example:

`Error from server (Forbidden): error when creating "examples/2x2x2/danielvm-maxtext.yaml": admission webhook "vjobset.kb.io" denied the request: must be no more than 63 characters` (notice it doesn't mention WHAT is longer than 63 characters, which may confuse the user.

Proposed error message: `Error from server (Forbidden): error when creating "examples/2x2x2/danielvm-maxtext.yaml": admission webhook "vjobset.kb.io" denied the request: JobSet name must be shorter; pod names generated for this JobSet will exceed 63 characters.`

What do you think? @ahg-g @kannon92

**Comment by ahg-g** [comment]
+1 to making the error message clearer.

Please also revisit the messages that we return when failing validation for follower pods because of not yet scheduled leader, perhaps we can make those clearer too.

**Comment by danielvegamyhre** [comment]
> +1 to making the error message clearer.
> 
> Please also revisit the messages that we return when failing validation for follower pods because of not yet scheduled leader, perhaps we can make those clearer too.

Yeah those seem to confuse users, I updated the error message to include the leader pod name and changed it to INFO instead of ERROR so users don't think something is wrong: https://github.com/kubernetes-sigs/jobset/pull/421

**Comment by danielvegamyhre** [comment]
Published patch release v0.3.2 today https://github.com/kubernetes-sigs/jobset/releases/tag/v0.3.2
