### ISSUE TITLE
Define variables in md language instead of having to update it in multiple places for every documentation update

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#425]
Define variables in md language instead of having to update it in multiple places for every documentation update

**Comment by uroy-personal** [comment]
Hi @danielvegamyhre ,
I am interested to work on this. Could you please provide more info on the change. An implementation example will also help.
I see four md files in the project ( README.md, RELEASE.md, SECURITY.md & CONTRIBUTING.md ), Do I need to created additional md files? Thanks.

**Comment by uroy-personal** [comment]
Hi @danielvegamyhre ,
I see the above file path does not exist. Should I check https://jobset.sigs.k8s.io/docs/installation file and put the md variable for VERSION if it is not present at the moment? Please advise. Thanks.

**Comment by danielvegamyhre** [comment]
Yes we moved all the docs into the site/content/en directory.

**Comment by danielvegamyhre** [comment]
Sure go ahead, that would be helpful

**Comment by uroy-personal** [comment]
Sorry guys. Having bit of hectic times recently. Unassigning it for the time-being. Will look foreward to this repo for future work scopes.
