### ISSUE TITLE
Introduce `managedBy` field

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/jobset#440]
**What would you like to be added**:
Remove the `alpha.jobset.sigs.k8s.io/managed-by` label and introduce `.spec.managedBy` field.

@mimowo @ahg-g @alculquicondor WDYT?

/kind feature

**Why is this needed**:
Since https://github.com/kubernetes-sigs/jobset/pull/407, we introduced the new `managed-by` label based on the batch/job KEP: https://github.com/kubernetes/enhancements/pull/4370.

But, we decided to introduce  a new `managedBy` field to batch/job here: https://github.com/kubernetes/enhancements/pull/4530
So, I think that we should use the `managedBy` field instead of the dedicated label as well as batch/job.

**Comment by ahg-g** [comment]
We added in the previous release, see https://github.com/kubernetes-sigs/jobset/issues/379

**Comment by alculquicondor** [comment]
+1 for replacing with a field.

I suppose the alpha annotation already made it to the release. I would suggest keeping both mechanism for at least one release, to facilitate upgrades to Kueue+Jobset.

**Comment by tenzen-y** [comment]
> +1 for replacing with a field.
> 
> I suppose the alpha annotation already made it to the release. I would suggest keeping both mechanism for at least one release, to facilitate upgrades to Kueue+Jobset.

That makes sense.

**Comment by kannon92** [comment]
I tried a quick revert option on the PR but that failed so reverting may be a bit of a manual process..

**Comment by mimowo** [comment]
+1 for using field, for ecosystem consistency, but also so that we fail fast when someone tries to use it on an old version (same argument as for the k8s job).

**Comment by danielvegamyhre** [comment]
@trasc have you already started this? I was hoping to have a team member of mine work on this as a good first issue to ramp up on JobSet, we just hadn't assigned it to him yet, so i'd like to assign it to them if that's okay

**Comment by trasc** [comment]
@danielvegamyhre Not yet.

/unassign

**Comment by danielvegamyhre** [comment]
Thanks!

/assign @jedwins1998

**Comment by kannon92** [comment]
What is our deprecation policy for the managed-by label?

**Comment by danielvegamyhre** [comment]
Update: we can safely drop the label entirely per conversation here https://github.com/kubernetes-sigs/kueue/pull/1870#discussion_r1536007381

**Comment by danielvegamyhre** [comment]
Some additional notes for implementation: 

- Add a JobSetSpec field analogous to the one in the JobSpec [here](https://github.com/kubernetes/kubernetes/blob/227c2e7c2b2c05a9c8b2885460e28e4da25cf558/pkg/apis/batch/types.go#L484). 
- Replace references to label with the field in jobset controller, unit tests, and integration tests
- Regenerate manifests: `make manifests`
- Regenerate Go and Python SDKs: `make generate`
- Ensure all unit, integration, e2e tests are passing: 
   - unit: `make test`
   - integration: `make test-integration`
   - e2e: `make test-e2e-kind`
- Run `make verify` to run linter, go vet, etc and make sure api/, config/, client-go/ are all updated together.
  
 @jedwins1998 you can generalize this into an improved contributor guide like you were talking about as well

**Comment by jedwins1998** [comment]
Created https://github.com/kubernetes-sigs/jobset/pull/487 as an initial implementation.

**Comment by jedwins1998** [comment]
PR has been merged. Will this issue auto-close or is there something I need to do?

**Comment by danielvegamyhre** [comment]
> PR has been merged. Will this issue auto-close or is there something I need to do?

It will auto-close if you add "Fixes #issueNumber" in the issue description. We can close this one manually. Thanks for your work on this!
