### ISSUE TITLE
Investigate ways to reduce or eliminate logging the error "ERROR the object has been modified; please apply your changes to the latest version and try again"

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#445]
**What would you like to be added**:
Investigate ways to reduce or eliminate logging the error "object has been modified; please apply your changes to the latest version and try again." 

Typically, this particular error is transient and expected - if process 1 fetches a k8s object state from the apiserver, then process 2 modifies the object state in the apiserver, then process 1 attempts to modify the object, it will get this error indicating the version of the object is outdated and it needs to re-fetch the latest object state before applying the update.

This error will trigger another reconcile attempt, which it will fetch the object and attempt to apply the update again, and this cycle will continue until it eventually succeeds.

**Why is this needed**:
The JobSet controller logs are filled with this error, which is confusing as well as the integration test output. It is confusing to users  looking at jobset logs to debug issues.

Also the integration test logs are polluted with this error, which is irksome for developers and confusing to new contributors.

**Comment by ahg-g** [comment]
The reason is this https://github.com/kubernetes-sigs/jobset/issues/405

**Comment by danielvegamyhre** [comment]
I see, ok thanks, I will close this issue in favor of the existing one.

**Comment by ahg-g** [comment]
Addressed in https://github.com/kubernetes-sigs/jobset/issues/747
