### ISSUE TITLE
Startup Policy Task demonstrating leader-worker pattern

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#449]
**What would you like to be added**:
Startup Policy Task demonstrating leader-worker pattern added to [tasks](https://github.com/kubernetes-sigs/jobset/tree/main/docs/tasks)

**Why is this needed**:
This is so users are aware of the feature and have an e2e example to get started with it.

**Comment by kannon92** [comment]
I have used https://github.com/kubernetes-sigs/jobset/blob/main/examples/simple/success-policy.yaml in presentations to demonstrate a leader-worker pattern where leader is terminated once the workers are finished.

**Comment by danielvegamyhre** [comment]
> I have used https://github.com/kubernetes-sigs/jobset/blob/main/examples/simple/success-policy.yaml in presentations to demonstrate a leader-worker pattern where leader is terminated once the workers are finished.

Yeah that example is great, I think we just need to add it [here](https://jobset.sigs.k8s.io/docs/tasks/#simple-examples) so the docsite is up to date with the latest features.

**Comment by danielvegamyhre** [comment]
/assign

Fixed by #453
