### ISSUE TITLE
Add e2e test setup and first test

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#46]
Similar to Kueue, we can start with kind

See kueue issue: https://github.com/kubernetes-sigs/kueue/issues/61

Main PRs: 
- https://github.com/kubernetes/test-infra/pull/27868
- https://github.com/kubernetes-sigs/kueue/pull/421

**Comment by danielvegamyhre** [comment]
With #74 submitted this is now complete.
