### ISSUE TITLE
default resource request should be lower so it fits on e2-medium

### ISSUE THREAD

**Issue by samos123** [kubernetes-sigs/jobset#462]
**What would you like to be added**:
default resource request should be lower so it fits on e2-medium

**Why is this needed**:

Too many people struggle to figure out why their jobset controller can't schedule on a default GKE cluster that uses e2-medium.

**Comment by danielvegamyhre** [comment]
> **What would you like to be added**: default resource request should be lower so it fits on e2-medium
> 
> **Why is this needed**:
> 
> Too many people struggle to figure out why their jobset controller can't schedule on a default GKE cluster that uses e2-medium.

I agree this is an annoying "gotcha" but reduced resource requests may result in poor performance at very large scales.  Let me see if we can reduce the default request but allow for templating or some way for a user to easily increase it for large scale use cases.

**Comment by ahg-g** [comment]
lowering requests and keeping limits high sounds good to me
