### ISSUE TITLE
Investigate solution to CRD being too large to use `kubectl apply`

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#47]
Currently the `make install` and `make deploy` commands won't work if the CRD / controller already exist on the cluster, since instead of doing `kubectl apply` they are both doing `kubectl create` now since the CRD is too large for `kubectl apply` as it runs into this [issue](https://github.com/kubernetes-sigs/kubebuilder/issues/1140). 

I'm guessing this will be an unexpected user experience for users so we need to figure how will someone update their existing deployment without interruptions if only kubectl create works (implying they must delete then recreate). Alternatively, we need to figure out how to reduce the size of the CRD.

**Comment by ahg-g** [comment]
It seems doing server-side apply solves it: https://github.com/SeldonIO/seldon-core/issues/4708

See how Kueue does it: https://github.com/kubernetes-sigs/kueue/blob/main/Makefile#L213
