### ISSUE TITLE
Add pod controller unit tests

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#478]
**What would you like to be added**:
Unit tests for https://github.com/kubernetes-sigs/jobset/blob/main/pkg/controllers/pod_controller.go in a pod_controller_test.go file.

Should use a fake client with interceptor functions as described [here](https://github.com/kubernetes-sigs/jobset/pull/473#discussion_r1537055795) to verify we delete the follower pods when the leader pod's topology does not match.

**Why is this needed**:
For improved test coverage.

**Comment by googs1025** [comment]
Do we need to close this issue? @danielvegamyhre
