### ISSUE TITLE
Consider adding exclusiveness api at the jobset level

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#48]
The current api is enforced at the job level, it is worth considering adding it at the jobset level as well.

**Comment by danielvegamyhre** [comment]
@ahg-g can you clarify the use case for this? Also, I think making exclusive placement be configurable at different levels (Job, ReplicatedJob, JobSet) could be part of the larger project of defining a formal Placement Policy API to replace the annotation, so perhaps we can close this and instead have an umbrella issue for the Placement Policy API.

**Comment by ahg-g** [comment]
Sounds good
