### ISSUE TITLE
Update installation docs with guidance on how to patch controller-manager resource requests for prod deployments

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#481]
**What would you like to be added**:
For production deployments the JobSet controller manager resource requests and limits should be configured to align with the specific infrastructure it will be deployed on. 

We should add guidance in the installation docs showing the user how to patch the deployment resource requests/limits for prod deployments: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-a-strategic-merge-patch-to-update-a-deployment

**Why is this needed**:
We need to lower the default resource requests to address a widespread usability issue users encounter when trying out JobSet for the first time and getting confused when they can't create JobSets after installing the CRD (controller manager pod stays pending due to not fitting on default cloud VM nodes). However, for production deployments users should not rely on the defaults and should patch them to be optimized for their prod deployment infrastructure.

**Comment by kannon92** [comment]
I think the doc should be more about how to use kustomize to deploy to a cluster and change the resource/requests.

I don't think patching the deployment is the right approch.

**Comment by danielvegamyhre** [comment]
Sure, Kustomize is fine as well

**Comment by omerap12** [comment]
Ill take it.
/assign
