### ISSUE TITLE
Implement Containerized Testing

### ISSUE THREAD

**Issue by jedwins1998** [kubernetes-sigs/jobset#492]
The current testing setup requires a user to perform a lot of setup on their bare metal machine for everything to work. It would be a nice improvement if all the setup could be done in a container that users could pull to perform their testing.

**Comment by kannon92** [comment]
:heart:

**Comment by jedwins1998** [comment]
Upstream K8s test docs that use containers https://github.com/kubernetes/kubernetes/blob/ec301a5cc76f48cdadc77bcfbd686cf40b124ecf/build/README.md

**Comment by kannon92** [comment]
I really want a devcontainer and I tried to bring it up https://github.com/kubernetes-sigs/kubebuilder/issues/3432 here.

Mostly I was hoping that one could use kubebuilder, generate the code and have at least a template for devcontainers/devpods.

I don't have that much experience in this area but that would be my wishlist.

I think e2e tests are difficult as kind doesn't support that AFAIK. But that could be one area to explore.
