### ISSUE TITLE
Atomic startup for main containers in a JobSet

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#498]
**What would you like to be added**:

Synchronized (all or nothing) startup for main containers in a JobSet.

**Why is this needed**:

Many users of managed K8s services on cloud providers make use of NAP (node auto provisioning) which creates node pools for pending/unschedulable pods, based on those pods requirements (i.e., CPU/memory requirements, GPU/TPU requirements, etc).

Since node pool provisioning takes a variable amount of time, users are running into issues where the first slice finishes provisioning and pods land there and begin running, but eventually timeout before the other slices all finish provisioning and pods land there and become ready.

Up til this point, this gap (lack of synchronized container startup) has been masked by scheduling happening fast enough that the timeouts in other parts of the stack (LibTPU, ML Frameworks, etc) don't get hit.

However, in this case the variability in slice provisioning time causes the timeouts to be hit.

One improvement to this will come with atomic scale ups via ProvisioningRequest down the road. However, that will just continue to mask/hide the lack of synchronized startup for a bit longer, and at large scales where scheduling all the pods takes substantial time, we still need synchronized startup.

**Comment by alculquicondor** [comment]
/retitle Atomic startup for main containers in a JobSet
