### ISSUE TITLE
Add some EventRecorder events from jobset

### ISSUE THREAD

**Issue by googs1025** [kubernetes-sigs/jobset#506]
**What would you like to be added**:
I noticed that the events generated by EventRecorder are not comprehensive enough. I plan to add more events in the controller, such as events for handling deletion errors or generating some common errors
**Why is this needed**:
The events generated by EventRecorder can be viewed for more critical events when executing kubectl describe jobset.

**Comment by googs1025** [comment]
@danielvegamyhre @kannon92 Can I attempt to enhance this feature?

**Comment by googs1025** [comment]
I'm not sure if the pod controller also needs the related events generated by EventRecorder. I don't think we would specifically look at the pods generated by the jobset.

**Comment by danielvegamyhre** [comment]
> **What would you like to be added**: I noticed that the events generated by EventRecorder are not comprehensive enough. I plan to add more events in the controller, such as events for handling deletion errors or generating some common errors **Why is this needed**: The events generated by EventRecorder can be viewed for more critical events when executing kubectl describe jobset.

I don't think an event for failing to delete a job is needed. Failing to create jobs is what we care about more; specifically, the first failed job which led to the jobset failing. We have an event emitted for this already.

**Comment by googs1025** [comment]
@danielvegamyhre  I have also added events for the failure to delete a job and the failure to create a headless service. So, the meaning is to keep the latter and remove the former, right?

**Comment by googs1025** [comment]
Done！thanks @danielvegamyhre @kannon92
