### ISSUE TITLE
Issue generating manifests 

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#508]
I am unable to run `make generate`.

Using the latest main, my environment seems to be stuck on generating code.

```
kehannon@kehannon-thinkpadp1gen4i:~/Work/jobset$ pwd
/home/kehannon/Work/jobset
kehannon@kehannon-thinkpadp1gen4i:~/Work/jobset$ make generate
test -s /home/kehannon/Work/jobset/bin/controller-gen && /home/kehannon/Work/jobset/bin/controller-gen --version | grep -q v0.14.0 || \
GOBIN=/home/kehannon/Work/jobset/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0
cp -f /home/kehannon/.gobrew/current/go/bin/pkg/mod/k8s.io/code-generator@v0.29.3/generate-groups.sh /home/kehannon/Work/jobset/bin/
cp -f /home/kehannon/.gobrew/current/go/bin/pkg/mod/k8s.io/code-generator@v0.29.3/generate-internal-groups.sh /home/kehannon/Work/jobset/bin/
cp -f /home/kehannon/.gobrew/current/go/bin/pkg/mod/k8s.io/code-generator@v0.29.3/kube_codegen.sh /home/kehannon/Work/jobset/bin/
/home/kehannon/Work/jobset/bin/openapi-gen --go-header-file hack/boilerplate.go.txt -i sigs.k8s.io/jobset/api/jobset/v1alpha2 -p sigs.k8s.io/jobset/api/jobset/v1alpha2 --alsologtostderr
2024/04/12 15:11:11 OpenAPI code generation error: Failed making a parser: unable to add directory "sigs.k8s.io/jobset/api/jobset/v1alpha2": No files for pkg "sigs.k8s.io/jobset/api/jobset/v1alpha2"
make: *** [Makefile:243: openapi-gen] Error 1
```

Does anyone else have this problem?

I realize that I am not following best practices about making sure your code is in $GOPATH but that hasn't been an issue before.

**Comment by kannon92** [comment]
I do not have any issues in Kueue with running `make generate`. Kueue doesn't use openapi-gen though.

**Comment by kannon92** [comment]
Well, if I change v1alpha2 to v1alpha1, I can get everything to generate...

**Comment by kannon92** [comment]
@ahg-g and @danielvegamyhre 

I am at a loss on what is going on.

If I change v1alpha2 to v1alpha (rename the api folder), code generation works.

I could also bump this to v1beta1 and I can get the generation to work.

If I leave it as v1alpha2, it fails.

Maybe one of you can try on a fresh repo (`make generate manifests`) is all I am doing. 

I noticed that I wasn't generating the CRDs anymore in a previous PR but nothing seemed work. Once I tried running this, it started failing.

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/jobset/pull/509 is my changings.

We probably don't want this as downgrading an API looks sus.

**Comment by kannon92** [comment]
I could create a PR to bump our APIs to v1beta1 and that allows me to build again..

**Comment by danielvegamyhre** [comment]
That's weird, I can't reproduce this issue so far

**Comment by ahg-g** [comment]
can you try this https://github.com/kubernetes-sigs/lws/issues/44#issuecomment-1985207696

**Comment by kannon92** [comment]
Yea I just don't understand why if I change v1alpha2 -> v1alpha1 or v1alpha2->v1beta1 it works without issue.

My gopath is set (I use gobrew so it points to 1.22.2 version).

```
kehannon@kehannon-thinkpadp1gen4i:~/Work/jobset$ echo $GOPATH
/home/kehannon/.gobrew/current/go/bin
```

I did a quick test and I keep the same gopath and I am able to run `make generate manifests` for both kueue and lws without any issue.

For jobset, it seems to be around the v1alpha2. But we didn't change that so I'm wondering if something happened with codegenerator.

**Comment by kannon92** [comment]
LWS, Kueue and JobSet all have a symbolic link to mock the GOPATH work. I have used this since I've developed for Kueue.

https://github.com/kubernetes-sigs/kueue/blob/main/hack/update-codegen.sh#L29

I have Kueue, LWS and JobSet (in $HOME/Work/REPO_NAME). Both Kueue and LWS work without issues on generation.

I also confirmed that the symbolic link is working for jobSet (if I uncomment the trap).

**Comment by danielvegamyhre** [comment]
> Not really sure what went wrong. I decided to give up on my golang environment (deleted cache, go environment) and redownloaded everything.
> 
> Once I did that I was back in action..

Ah that's annoying, glad you managed to sort it out though. So can we close this issue now?
