### ISSUE TITLE
Replace cert-manager with internal cert

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#52]
We don't want a dependency on cert-manager and it also complicates the user experience by requiring they install it on their cluster beforehand. We should migrate to using internal certs.

See https://github.com/kubernetes-sigs/kueue/pull/265 for example

**Comment by ahg-g** [comment]
It would be best to prioritize this and have it as part of 0.1.0 release.

**Comment by tenzen-y** [comment]
Hello, jobset community :)

Do you plan to provide the component config like kueue to enable configurable cert settings such as whether the users use internal cert or cert-manager and so on?

https://github.com/kubernetes-sigs/kueue/blob/9ca57c86cf06c11a94a2d5b7badf60233a51a2f2/config/components/manager/controller_manager_config.yaml

**Comment by ahg-g** [comment]
> Hello, jobset community :)
> 
> Do you plan to provide the component config like kueue to enable configurable cert settings such as whether the users use internal cert or cert-manager and so on?
> 
> https://github.com/kubernetes-sigs/kueue/blob/9ca57c86cf06c11a94a2d5b7badf60233a51a2f2/config/components/manager/controller_manager_config.yaml

Hello and welcome :)

Yes, for sure, do you mind opening an issue to track it?

**Comment by tenzen-y** [comment]
> > Hello, jobset community :)
> > Do you plan to provide the component config like kueue to enable configurable cert settings such as whether the users use internal cert or cert-manager and so on?
> > https://github.com/kubernetes-sigs/kueue/blob/9ca57c86cf06c11a94a2d5b7badf60233a51a2f2/config/components/manager/controller_manager_config.yaml
> 
> Hello and welcome :)
> 
> Yes, for sure, do you mind opening an issue to track it?

Oh, sounds great!
I will create an issue, and I will help with introducing the component config to the JobSet.
