### ISSUE TITLE
Periodic Jobs for Testing Release Branches

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#524]
Kueue has periodics that run on the release branches.

JobSet currently only has presubmits on main. We should have tests on our release branches and we should also have periodics jobs.

**Comment by kannon92** [comment]
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kueue/kueue-release-blocking.yaml

Is at least the periodics. They run on main for every 12 hours.

It looks like kueue has presubmits for release branches actually.

**Comment by omerap12** [comment]
PR: https://github.com/kubernetes/test-infra/pull/32532

**Comment by danielvegamyhre** [comment]
This was completed in https://github.com/kubernetes/test-infra/pull/32532
