### ISSUE TITLE
Add metrics to reflect controller health

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#53]
Possible metrics:

- Reconciliation latency
- Reconciliation failures 
- JobSets waiting to be processed (we need to look at controller-runtime if it exposes something)

**Comment by charles-chenzz** [comment]
does this issue urgent? might need some time to check how to implement metrics

**Comment by ahg-g** [comment]
https://github.com/kubernetes-sigs/jobset/issues/60 is more urgent, can you remove the CEL validation and just validate inside the webhook?

**Comment by charles-chenzz** [comment]
I need to check first, not sure if I know how to do it :(

**Comment by danielvegamyhre** [comment]
Seems like Reconciliation Latency and Reconciliation Failures are already captured via controller-runtime prometheus metrics here: https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/internal/controller/metrics/metrics.go#L37-L44

**Comment by ahg-g** [comment]
/re-open

We need to add docs explaining the couple of metrics you mentioned above, similar to https://kueue.sigs.k8s.io/docs/reference/metrics/
