### ISSUE TITLE
Bug in testing utility function JobSetActive

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#530]
@jedwins1998 encountered a bug when working on tests for configurable failure policy changes, tests would pass when using `JobSetFailed()` to check the JobSet has a failed condition type with a status of true, but also would pass when `JobSetFailed()` was changed to `JobSetActive()`. 

I think this is because in [JobSetActive](https://github.com/kubernetes-sigs/jobset/blob/9dc4358670f119164517f90d6005bd4742a4ff5d/test/util/util.go#L120) we are simply passing in an empty list of conditions to checkJobSetStatus, which verifies all given conditions are set on the jobset status. 

However, even for a failed JobSet, the number of conditions matching an empty list of conditions will be 0, and the check will return ok, which it should not.

Instead, we should change JobSetActive to verify there are no mutually exclusive conditions set on the JobSet status, like failed or completed.

**Comment by jedwins1998** [comment]
The JobSet condition types are defined [here](https://github.com/kubernetes-sigs/jobset/blob/9dc4358670f119164517f90d6005bd4742a4ff5d/api/jobset/v1alpha2/jobset_types.go#L51).

I am planning to apply the definition that a JobSet is considered active as long as none of the following conditions have a status of true:
1. JobSetCompleted,
1. JobSetFailed,
1. JobSetSuspended.

In particular, an active JobSet can still have the conditions JobSetStartupPolicyInProgress and JobSetStartupPolicyCompleted with any given status. Do others see issues with this definition?
