### ISSUE TITLE
docs: Add an example YAML file for the usage of the 'network' field.

### ISSUE THREAD

**Issue by googs1025** [kubernetes-sigs/jobset#548]
**What would you like to be added**:
I noticed that there are no relevant examples for the 'network' field in examples/simple. I would like to add an example in examples/simple, for instance, on how to use the 'Subdomain' and 'PublishNotReadyAddresses' fields. Additionally, I would like to document how to access pods through a headless service.
**Why is this needed**:
Let users know how to access each other's pods in the jobset through headless svc

**Comment by googs1025** [comment]
@kannon92 @danielvegamyhre @ahg-g  Do we need it?

**Comment by ahg-g** [comment]
Most existing examples already use that, but I am ok if you want to add something under https://github.com/kubernetes-sigs/jobset/tree/main/examples/simple
