### ISSUE TITLE
Provide the component config

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/jobset#55]
I would like to provide the component config like kueue: https://github.com/kubernetes-sigs/kueue/blob/9ca57c86cf06c11a94a2d5b7badf60233a51a2f2/config/components/manager/controller_manager_config.yaml

Maybe, as a first step, we can provide the functionality for users to select whether to use the internal cert or the cert-manager.

/kind feature

ref: #52

**Comment by tenzen-y** [comment]
The component-config is deprecated and will be removed. So we should hold similar schemes as component-config in this repository.

ref: https://github.com/kubernetes-sigs/kueue/issues/725

**Comment by tenzen-y** [comment]
Maybe, I don't have enough time to work on this.

/unassign

**Comment by charles-chenzz** [comment]
I can take it up. do you have any idea on how to implement it or any examples that I can refer to? @tenzen-y 
/assign

**Comment by charles-chenzz** [comment]
can you be more specify about the ref and implement? I think adding this feature will require us to use code-gen to gen the file and implement the function. then there comes a the key question is: do we actually need this? and are there any more scenes that might need this api/feature?(beside internal-cert and cert manager) @tenzen-y 

also /cc @ahg-g  for advice

**Comment by ahg-g** [comment]
> an you be more specify about the ref and implement? I think adding this feature will require us to use code-gen to gen the file and implement the function.

see https://book.kubebuilder.io/component-config-tutorial/tutorial.html

> and are there any more scenes that might need this api/feature?(beside internal-cert and cert manager)
kube connection configuration is important to have to set qps limits, similar to https://github.com/kubernetes-sigs/kueue/blob/main/apis/config/v1beta1/configuration_types.go#L57.

**Comment by tenzen-y** [comment]
> do we actually need this? and are there any more scenes that might need this api/feature?

If we introduce the component config, we can set up many parameters for the controller besides the cert.

Note: ComponentConfig is deprecated. So we must implement all features of the https://github.com/kubernetes-sigs/controller-runtime/tree/30dea34848b0e0b30690dd461a0eadb74d4869f3/pkg/config in this repo.

**Comment by charles-chenzz** [comment]
> Note: ComponentConfig is deprecated. So we must implement all features of the https://github.com/kubernetes-sigs/controller-runtime/tree/30dea34848b0e0b30690dd461a0eadb74d4869f3/pkg/config in this repo.

thanks for the heads up, then I need to check this link and see how to implement it.

**Comment by tenzen-y** [comment]
> > Note: ComponentConfig is deprecated. So we must implement all features of the https://github.com/kubernetes-sigs/controller-runtime/tree/30dea34848b0e0b30690dd461a0eadb74d4869f3/pkg/config in this repo.
> 
> thanks for the heads up, the files said user need to migrate to their own. what it means is that we need to copy the struct to our own repo's codebase or we implement it in some other ways? @tenzen-y

Yes, you're right.

**Comment by danielvegamyhre** [comment]
@charles-chenzz I assume you aren't working on this anymore so i'm going to unassign it, but if you want to implement this please feel free to reassign.

**Comment by rainfd** [comment]
@tenzen-y only implement cert management in this issue?

**Comment by rainfd** [comment]
```yaml
apiVersion: config.jobset.x-k8s.io/v1alpha1
kind: Configuration
namespace: jobset-system
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8080
leaderElection:
  leaderElect: true
webhook:
  port: 9443
clientConnection:
  qps: 50
  burst: 100
internalCertManagement:
  enable: false
  webhookServiceName: ""
  webhookSecretName: ""
```
The basic configuration, same as kueue?

```yaml
leaderElection:
  leaderElect: true
  resourceName: c1f6bfd2.jobset.x-k8s.io
```
Do we need to change the leaderelectionid?
@tenzen-y

**Comment by tenzen-y** [comment]
> @tenzen-y only implement cert management in this issue?

I assumed that we could provide a similar functionality as Kueue.
So, it would be useful if we could provide the functionality to modify controller manager options like client qps.

**Comment by tenzen-y** [comment]
> ```yaml
> apiVersion: config.jobset.x-k8s.io/v1alpha1
> kind: Configuration
> namespace: jobset-system
> health:
>   healthProbeBindAddress: :8081
> metrics:
>   bindAddress: :8080
> leaderElection:
>   leaderElect: true
> webhook:
>   port: 9443
> clientConnection:
>   qps: 50
>   burst: 100
> internalCertManagement:
>   enable: false
>   webhookServiceName: ""
>   webhookSecretName: ""
> ```
> 
> The basic configuration, same as kueue?
> 
> ```yaml
> leaderElection:
>   leaderElect: true
>   resourceName: c1f6bfd2.jobset.x-k8s.io
> ```
> 
> Do we need to change the leaderelectionid? @tenzen-y

Generally, looks great.
Thank you for proposing the design!
