### ISSUE TITLE
Add support for feature gates

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes-sigs/jobset#556]
**What would you like to be added**:

Add support for feature gates in JobSet, like are used in upstream k8s and Kueue [here](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/features/kube_features.go).

**Why is this needed**:
- Allow customer to quickly disable a feature if a bug is detected
- Allow us to have "opt-in" features that are off by default.

**Comment by googs1025** [comment]
Do we need to discuss which feature gates need to be added?

**Comment by googs1025** [comment]
I have been thinking, can we include these two items in the feature gate? They can be enabled by default, and if there are more features in the future, they can be added. @danielvegamyhre 
`Establishment of a headless service`
`TTL after finished`

**Comment by danielvegamyhre** [comment]
I don't think we can (or should) put existing features behind feature gates, it would be weird for the feature gate to exist on some versions but not others. I think we should put new features (not released yet) which are somewhat risky behind a feature gate. Not sure off the top of my head if this aligns with upstream k8s standard practices, @kannon92 do you know?

**Comment by googs1025** [comment]
Understood. As far as I understand, the current features of JobSet are all existing ones, and there are no new unstable features yet. In that case, we can provide the feature gate functionality for other developers to use, but without any default configuration. How does that sound?
