### ISSUE TITLE
Publish JobSet API reference

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/jobset#566]
**What would you like to be added**:

API reference for the JobSet API. Similarly as for Kueue: https://kueue.sigs.k8s.io/docs/reference/kueue.v1beta1/

**Why is this needed**:

So that we can easily reference JobSet API from the Kueue project.

**Comment by danielvegamyhre** [comment]
@mimowo is this auto-generated in Kueue?

**Comment by mimowo** [comment]
yes, it is done by the [`generate-apiref`](https://github.com/kubernetes-sigs/kueue/blob/c55f10ceb88a356deeb67bab0706db2e6f21c6ab/Makefile#L321) goal

**Comment by sandipanpanda** [comment]
Hi, I am interested in working on this to familiarize myself with this sub-project. As this is a [good first issue](https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md#good-first-issue), can you provide some context and the recommended solution?

/assign

**Comment by sandipanpanda** [comment]
Can this tool be used? https://github.com/ahmetb/gen-crd-api-reference-docs

**Comment by danielvegamyhre** [comment]
@sandipanpanda Sure, it would be great if you want to work on this. As a starting point, take a look at how Kueue generates api reference [here](https://github.com/kubernetes-sigs/kueue/blob/c55f10ceb88a356deeb67bab0706db2e6f21c6ab/Makefile#L321) and see if we can do the same thing in JobSet.

**Comment by danielvegamyhre** [comment]
@sandipanpanda are you still working on this?

**Comment by googs1025** [comment]
If this issue is free, I will take it. After https://github.com/kubernetes-sigs/jobset/pull/594 merge

**Comment by ahg-g** [comment]
/assign @googs1025 

Thanks!

**Comment by googs1025** [comment]
/close 
https://github.com/kubernetes-sigs/jobset/pull/611 fixed this issue
