### ISSUE TITLE
The e2e tests on 1.28 fail consistently

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/jobset#583]
Dashboards:
https://testgrid.k8s.io/sig-scheduling#periodic-jobset-test-e2e-release-0-5-1-28
https://testgrid.k8s.io/sig-scheduling#periodic-jobset-test-e2e-release-0-4-1-28
https://testgrid.k8s.io/sig-scheduling#periodic-jobset-test-e2e-main-1-28

Example history:
![image](https://github.com/kubernetes-sigs/jobset/assets/10359181/14cce43b-daf4-488d-afc6-d6acc374706a)

Example log:
```
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.28.3) 🖼  ...
 ✗ Ensuring node image (kindest/node:v1.28.3) 🖼
ERROR: failed to create cluster: failed to pull image "kindest/node:v1.28.3": command "docker pull kindest/node:v1.28.3" failed with error: exit status 1
```

I suppose this is because there is no 1.28.3 image available for kindest/node on dockerhub.

**Comment by mimowo** [comment]
cc @danielvegamyhre

**Comment by danielvegamyhre** [comment]
/assign

Thanks @mimowo

**Comment by danielvegamyhre** [comment]
Created https://github.com/kubernetes/test-infra/pull/32677

**Comment by danielvegamyhre** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/32677
