### ISSUE TITLE
Run Job validation on the templates as part of JobSet validation

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#59]
This is a better experience vs catching such problems at runtime when jobset attempts to create the job.

**Comment by kannon92** [comment]
Do you know how you should do validation?  I know k/k has a validation package but not as clear what users of api libraries have.

**Comment by kannon92** [comment]
@ahg-g AFAIK we tried this but found that there isn’t really a way to use job code for validation. I think we can close this issue.

/close
