### ISSUE TITLE
Setup validation and defaulting webhook

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#6]

**Comment by ahg-g** [comment]
Using CEL would certainly be better, lets start with that and see how far we can go. Does it cover defaulting too?

**Comment by ahg-g** [comment]
Things to validate:
- EnableDNSHostnames is allowed only with completion mode Indexed.

**Comment by kannon92** [comment]
Should we close this issue?

**Comment by ahg-g** [comment]
Yes

**Comment by ahg-g** [comment]
/reopen

we need to enforce immutability of most fields in the JobSetSpec, I think the only field we should allow for now is suspend

**Comment by ahg-g** [comment]
We may need to setup a defaulting webhook if we are to default things within the job template, like Indexed mode.
