### ISSUE TITLE
Invalid validation on Network field

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#60]
When not set, validation fails when creating a JobSet, I think something is wrong with the CEL validation at https://github.com/kubernetes-sigs/jobset/blob/main/api/v1alpha1/jobset_types.go#L83

Probably better to move this to the validation webhook, that validation line is hard to reason about.

/kind bug

**Comment by tenzen-y** [comment]
Creating the integration tests for validation webhook might be worth it to avoid such bugs.

**Comment by kannon92** [comment]
#63 I believe solves this issue.

/close
