### ISSUE TITLE
Default restartPolicy

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/jobset#61]
Job only accepts only Never or OnFailure restartPolicy. We can default it to Never since most HPC and ML training workloads don't tolerate failures and can only recover by restarting the whole job

**Comment by ahg-g** [comment]
/assign @danielvegamyhre 

lets default is to `OnFailure`

**Comment by danielvegamyhre** [comment]
@ahg-g Since we removed `RestartPolicy` in #65 only has the field `MaxRestarts` I assume we can do this later on, once we support multiple types of restart policies again right?

**Comment by ahg-g** [comment]
I am actually referring to the restartPolicy of the containers

**Comment by danielvegamyhre** [comment]
Ah ok that makes more sense, ok I'll work on this today.
