### ISSUE TITLE
[bug] Kueue with Jobset automatically suspends child job

### ISSUE THREAD

**Issue by tiffzhao5** [kubernetes-sigs/jobset#616]
Opened an issue on the Kueue side, but unsure if this is a Jobset bug given that a k8s batchv1Job works perfectly fine with Kueue. Please help, thank you!

https://github.com/kubernetes-sigs/kueue/issues/2612

**Comment by kannon92** [comment]
/close

Integration with Kueue is the issue here. Going to close so we can steer conversation on the Kueue issue.
