### ISSUE TITLE
Register labels/annotations on Kubernetes Website

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#639]
We should post the labels/annotations that JobSet uses on the k8s website in the official list.

Our labels are defined [here](https://github.com/kubernetes-sigs/jobset/blob/main/api/jobset/v1alpha2/jobset_types.go#L22).

We should post these on https://github.com/kubernetes/website/blob/main/content/en/docs/reference/labels-annotations-taints/_index.md

**Comment by sftim** [comment]
(yes please - and even the alpha ones)

**Comment by kannon92** [comment]
https://github.com/kubernetes/website/pull/47383

**Comment by danielvegamyhre** [comment]
This is duplicated by https://github.com/kubernetes/website/issues/47373 and is being worked on by @Adarsh-verma-14, it's almost done.
