### ISSUE TITLE
Active jobs are not deleted when the job finishes if TTLSecondsAfterFinished is set

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/jobset#666]
**What happened**:

When `TTLSecondsAfterFinished` is not set, the active jobs get deleted right away to free up resources. However, when `TTLSecondsAfterFinished` is set, the active jobs and the completed jobs all get deleted after the TTL expires when the jobset itself gets deleted.

**What you expected to happen**:

`TTLSecondsAfterFinished` should control jobset cleanup but active jobs should be deleted regardless when a jobset is failed or complete to release resources.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- JobSet version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kannon92** [comment]
Hey @CecileRobertMichon 

Thank you for the issue and the PR to fix it. We have a few CI issues I’m trying to fix this week so I’ll get to reviewing your PR soon.
